-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 00:07:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documentos` (
  `idDocumentos` VARCHAR(8) NOT NULL,
  `filePath` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocumentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `idSucursal` VARCHAR(8) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compras` (
  `idCompras` VARCHAR(8) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Documentos_idDocumentos` VARCHAR(8) NOT NULL,
  `Sucursal_idSucursal` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idCompras`, `Documentos_idDocumentos`, `Sucursal_idSucursal`),
  CONSTRAINT `fk_Compras_Documentos1`
    FOREIGN KEY (`Documentos_idDocumentos`)
    REFERENCES `mydb`.`Documentos` (`idDocumentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitudes` (
  `idSolicitudes` VARCHAR(8) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `locationkey` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSolicitudes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Celulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Celulares` (
  `idCelulares` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Camara` VARCHAR(45) NOT NULL,
  `Carga` VARCHAR(45) NOT NULL,
  `Pantalla` VARCHAR(45) NOT NULL,
  `Dimensiones` VARCHAR(45) NOT NULL,
  `Resolucion` VARCHAR(45) NOT NULL,
  `Peso` VARCHAR(45) NOT NULL,
  `Tec` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Memoria` VARCHAR(45) NOT NULL,
  `OS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCelulares`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` VARCHAR(8) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Colonia` VARCHAR(45) NOT NULL,
  `CodigoPostal` VARCHAR(45) NOT NULL,
  `numExterior` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Compras_idCompras` VARCHAR(8) NOT NULL,
  `Solicitudes_idSolicitudes` VARCHAR(8) NOT NULL,
  `Solicitudes_Inventario_idInventario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idClientes`, `Compras_idCompras`, `Solicitudes_idSolicitudes`, `Solicitudes_Inventario_idInventario`),
  CONSTRAINT `fk_Clientes_Compras1`
    FOREIGN KEY (`Compras_idCompras`)
    REFERENCES `mydb`.`Compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_Solicitudes1`
    FOREIGN KEY (`Solicitudes_idSolicitudes`)
    REFERENCES `mydb`.`Solicitudes` (`idSolicitudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`confirmacion_Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`confirmacion_Documento` (
  `fechaLlegada` VARCHAR(8) NOT NULL,
  `idConfirmación` VARCHAR(45) NOT NULL,
  `Documentos_idDocumentos` VARCHAR(8) NOT NULL,
  CONSTRAINT `fk_confirmacion_Documento_Documentos1`
    FOREIGN KEY (`Documentos_idDocumentos`)
    REFERENCES `mydb`.`Documentos` (`idDocumentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rechazo_Documento` (
  `motivoRechazo` VARCHAR(45) NOT NULL,
  `Documentos_idDocumentos` VARCHAR(8) NOT NULL,
  CONSTRAINT `fk_table2_Documentos1`
    FOREIGN KEY (`Documentos_idDocumentos`)
    REFERENCES `mydb`.`Documentos` (`idDocumentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal_has_Celulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal_has_Celulares` (
  `Sucursal_idSucursal` VARCHAR(8) NOT NULL,
  `Sucursal_Inventario_idInventario` VARCHAR(8) NOT NULL,
  `Celulares_idCelulares` VARCHAR(8) NOT NULL,
  `cardinalidadCelular` INT NOT NULL,
  PRIMARY KEY (`Sucursal_idSucursal`, `Sucursal_Inventario_idInventario`, `Celulares_idCelulares`),
  CONSTRAINT `fk_Sucursal_has_Celulares_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_has_Celulares_Celulares1`
    FOREIGN KEY (`Celulares_idCelulares`)
    REFERENCES `mydb`.`Celulares` (`idCelulares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
