-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 21:22:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documentos` (
  `idDocumentos` VARCHAR(8) NOT NULL,
  `filePath` VARCHAR(45) NULL,
  PRIMARY KEY (`idDocumentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idInventario` VARCHAR(8) NOT NULL,
  `cantidadTotal` INT NULL,
  PRIMARY KEY (`idInventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `idSucursal` VARCHAR(8) NOT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `Inventario_idInventario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idSucursal`, `Inventario_idInventario`),
  INDEX `fk_Sucursal_Inventario1_idx` (`Inventario_idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursal_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compras` (
  `idCompras` VARCHAR(8) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `Documentos_idDocumentos` INT NOT NULL,
  `Sucursal_idSucursal` VARCHAR(8) NOT NULL,
  `Sucursal_Inventario_idInventario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idCompras`, `Documentos_idDocumentos`, `Sucursal_idSucursal`, `Sucursal_Inventario_idInventario`),
  INDEX `fk_Compras_Documentos1_idx` (`Documentos_idDocumentos` ASC) VISIBLE,
  INDEX `fk_Compras_Sucursal1_idx` (`Sucursal_idSucursal` ASC, `Sucursal_Inventario_idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_Compras_Documentos1`
    FOREIGN KEY (`Documentos_idDocumentos`)
    REFERENCES `mydb`.`Documentos` (`idDocumentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal` , `Sucursal_Inventario_idInventario`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal` , `Inventario_idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitudes` (
  `idSolicitudes` VARCHAR(8) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Inventario_idInventario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idSolicitudes`, `Inventario_idInventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Celulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Celulares` (
  `idCelulares` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idCelulares`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` VARCHAR(8) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Calle` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Colonia` VARCHAR(45) NULL,
  `CodigoPostal` VARCHAR(45) NULL,
  `numExterior` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Compras_idCompras` VARCHAR(8) NOT NULL,
  `Solicitudes_idSolicitudes` VARCHAR(8) NOT NULL,
  `Solicitudes_Inventario_idInventario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idClientes`, `Compras_idCompras`, `Solicitudes_idSolicitudes`, `Solicitudes_Inventario_idInventario`),
  INDEX `fk_Clientes_Compras1_idx` (`Compras_idCompras` ASC) VISIBLE,
  INDEX `fk_Clientes_Solicitudes1_idx` (`Solicitudes_idSolicitudes` ASC, `Solicitudes_Inventario_idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Compras1`
    FOREIGN KEY (`Compras_idCompras`)
    REFERENCES `mydb`.`Compras` (`idCompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_Solicitudes1`
    FOREIGN KEY (`Solicitudes_idSolicitudes` , `Solicitudes_Inventario_idInventario`)
    REFERENCES `mydb`.`Solicitudes` (`idSolicitudes` , `Inventario_idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario_has_Celulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario_has_Celulares` (
  `Inventario_idInventario` VARCHAR(8) NOT NULL,
  `Celulares_idCelulares` VARCHAR(8) NOT NULL,
  `cardinalidadCelulares` INT NULL,
  PRIMARY KEY (`Inventario_idInventario`, `Celulares_idCelulares`),
  INDEX `fk_Inventario_has_Celulares_Celulares1_idx` (`Celulares_idCelulares` ASC) VISIBLE,
  INDEX `fk_Inventario_has_Celulares_Inventario_idx` (`Inventario_idInventario` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_has_Celulares_Inventario`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_has_Celulares_Celulares1`
    FOREIGN KEY (`Celulares_idCelulares`)
    REFERENCES `mydb`.`Celulares` (`idCelulares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
